# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      # Linter 실행
      - id: ruff
        args: [ --fix, --output-format=github ]
      # Formatter 실행
      - id: ruff-format
        args: [ --preview, --output-format=github ]
